seed: 42
rounds: 5
seed_k: 200

rf:
  n_estimators: 300
  class_weight: balanced_subsample
  max_depth: null
  max_features: 'sqrt'
  n_jobs: -1

al:
  batch_B: 100
  per_class_min: 5

data:
  rsna_csv: data/path_embed_rsna.csv
  mendeley_csv: data/path_embed_mendeley.csv
  label_col: ivd_level
  id_col: id
  image_col: axial_path
  emb_col: null

mri_core:
  device: cuda
  batch_size: 2
  dtype: fp16
  image_size: 1024
  checkpoint: src/mri_foundation/checkpoint/mri_foundation.pth

augment:
  train_n_per_sample: 5
  tta_n_per_sample: 0

meta:
  enabled: true
  lambda: 1e-2
  oof_folds: 5
  include_T: false
  refresh_every: 1

qbc:
  score: js_to_mean
  blend_alpha: 0.0

logging:
  out_dir: runs/sim_meta_summary/
